In [1]:
import numpy as np
import pandas as pd
import csv
import json


In [2]:
data_file = r"../../../../InputData/Healthcare/incomeK/before_selection_incomeK.csv"
query_file_prefix = r"query3.json"

data = pd.read_csv(data_file, index_col=False)

print(data['num-children'].unique())
print(data['complications'].unique())



[2 4 0 3 1 5]
[ 8  9 10  7  6]


In [3]:
print(data.describe())


               id  num-children      income  complications
count   67.000000     67.000000   67.000000      67.000000
mean   537.029851      2.373134  372.567164       8.417910
std    302.376144      1.640730   40.720118       1.182566
min     18.000000      0.000000  300.000000       6.000000
25%    263.500000      1.000000  336.500000       7.000000
50%    542.000000      2.000000  376.000000       8.000000
75%    840.500000      4.000000  404.000000       9.000000
max    992.000000      5.000000  446.000000      10.000000


In [4]:
data["race"].unique()

array([nan, 'race1', 'race3', 'race2'], dtype=object)

In [118]:
# print(len(data))
# data1 = data[(data["income"] <= 50)]
# print(len(data1))
# print(len(data1)/len(data))

In [119]:

# data1 = data1[(data1["complications"] >= 5)]
# print(len(data1))
# print(len(data1)/len(data))


In [120]:

# data1 = data1[(data1["num-children"] >= 3)]
# print(len(data1))
# print(len(data1)/len(data))


# q3

In [121]:


print(len(data))
data1 = data[data['income'] <= 100]
print(len(data1))
data2 = data1[data1['complications'] >= 5]
print(len(data2))
data3 = data2[data2['num-children'] >= 4]
print(len(data3))

print(data3.groupby(['race']).size())

print(data3.groupby(['age-group']).size())

data = data3

887
313
137
42
race
race1    15
race2     7
race3    13
dtype: int64
age-group
group1    12
group2    15
group3    15
dtype: int64


In [122]:
relax_rate = 1.05
contract_rate = 0.95
relax_rate_change = [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
contract_rate_change = [0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

## relax

In [123]:
data1 = data[(data["race"] == "race2")]
print(len(data1))
print(len(data1) * relax_rate)

7
7.3500000000000005


In [124]:
for s in relax_rate_change:
    print(len(data1) * s)

7.700000000000001
8.4
9.1
9.799999999999999
10.5
11.200000000000001


In [125]:
data2 = data[(data["age-group"] == "group1")]
print(len(data2))
print(len(data2) * relax_rate)


12
12.600000000000001


# contract

In [126]:
data1 = data[(data["race"] == "race1")]
print(len(data1))
print(len(data1) * contract_rate)

15
14.25


In [127]:
for s in contract_rate_change:
    print(len(data1) * s)

6.0
7.5
9.0
10.5
12.0
13.5


In [129]:
data2 = data[(data["age-group"] == "group2")]
print(len(data2))
print(len(data2) * contract_rate)


15
14.25


In [130]:
data2 = data[(data["age-group"] == "group3")]
print(len(data2))
print(len(data2) * contract_rate)


15
14.25


# refine

In [131]:
data1 = data[(data["age-group"] == "group1")]
print(len(data1))
print(len(data1) * 1.05)


12
12.600000000000001


In [132]:
s = [1.02, 1.04, 1.06, 1.08, 1.10, 1.12]
for r in s:
    print(len(data1) * r)

12.24
12.48
12.72
12.96
13.200000000000001
13.440000000000001


In [133]:
data1 = data[(data["race"] == "race1")]
print(len(data1))
print(len(data1) * contract_rate)

15
14.25
